#!/bin/sh

# input feature directories
#  for example, we can use the lab files in ../TESTDATA/vctk_acous/lab_test
#  and the one-hot speaker vectors in ../TESTDATA/vctk_acous/spk_test
# 
export TEMP_ACOUSTIC_MODEL_INPUT_DIRS=$PWD/../TESTDATA/vctk_acous/lab_test/,$PWD/../TESTDATA/vctk_acous/spk_test/

# where is the directory of the trained model
export TEMP_ACOUSTIC_MODEL_DIRECTORY=$PWD/MODELS/RNN_001

# where is the trained model?
export TEMP_ACOUSTIC_NETWORK_PATH=$PWD/MODELS/RNN_001/trained_network.jsn

# where to store the features generated by the trained network?
export TEMP_ACOUSTIC_OUTPUT_DIRECTORY=$PWD/MODELS/RNN_001/output

# directory to save intermediate files (it will be deleted after)
export TEMP_ACOUSTIC_TEMP_OUTPUT_DIRECTORY=./tmp_int_out

# 
python ../SCRIPTS/03_syn.py config
# after running this scripts, the generated features should be in ${TEMP_ACOUSTIC_OUTPUT_DIRECTORY}

rm -r ${TEMP_ACOUSTIC_TEMP_OUTPUT_DIRECTORY}
